[package]
name = "Cinematch"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
actix-service = "2"
actix-http = "3"
openssl = { version = "0.10" }
actix-tls = "3"
env_logger = "0.11.5"
log = "0.4.22"
